### ISSUE TITLE
uniqueness & unsung heroics

### ISSUE THREAD

**Issue by TensorTom** [klahnakoski/mo-dots#1]
This is one of the coolest modules I've ever seen. How aren't there thousands of stars? Do you know of any similar lib?

**Comment by klahnakoski** [comment]
@TensorTom   Thank you for the kind words.  I certainly agree that this module is cool; but I realize it serves a specific domain of programming: JSON data transformation, usually found in ETL jobs.  

You will find variations of this library in many other code repositories; rarely is this type of code put into a stand alone module.  For those times it happens, I have a short list of similar libraries: https://github.com/klahnakoski/mo-dots/tree/dev/docs#examples-in-the-wild   If you find others, please tell me about it (or make a PR).

**Comment by TensorTom** [comment]
Here are some related packages I recently found:

https://dotty-dict.readthedocs.io/en/latest/

https://pypi.org/project/traversify/

https://glom.readthedocs.io/en/latest/

https://pypi.org/project/roam/

I'm currently working on a map & update package. I might just submit as PR to mo-dots.
