### ISSUE TITLE
3.141.20326 has conflicting requirements

### ISSUE THREAD

**Issue by xhochy** [klahnakoski/mo-dots#5]
The `mo-future` version that is pinned in https://github.com/klahnakoski/mo-dots/blob/fed6bfed9eb2ead926139916a9a551cd0d4a95c0/setup.py#L11 is different from the one that is pinned in the required `mo-dots` release: https://github.com/klahnakoski/mo-imports/blob/94093c0e3e489d496188adada22ba357b08b9e16/setup.py#L10 

Thus the latest release cannot be installed correctly.

**Comment by klahnakoski** [comment]
Thank you very much for pointing this out.   I will resolve this asap

**Comment by xhochy** [comment]
Thanks, I managed a rebuild of all conda packages up to `moz-sql-parser`. This is working again.
